// GET /api — API index (mirrors the future FastAPI /v1 surface).

import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    name: "TrustScore Platform API",
    stage: "12 — Transparency & Alerting (public policy explainer, material score-drop receipts, timer-driven webhook worker)",
    version: "1.11.0",
    notice:
      "NINAuth integration is implemented behind a contract-first MOCK provider adapter (OAuth 2.0 + PKCE + OIDC-style ID tokens). Phone (SMS OTP) and biometric (liveness) signals are likewise contract-first MOCK transports. No live government or MNO/biometric integration is claimed. The LIVE transports activate once partner sandbox credentials exist (audit §2.2). The B2B Trust Decision API and webhook deliveries are real integrations against that same MOCK-provider platform; plan billing is an honest mock-up (no payment processor is connected).",
    endpoints: [
      { method: "GET", path: "/api/health", auth: false, description: "Liveness + database readiness" },
      { method: "POST", path: "/api/v1/auth/register", auth: false, description: "Create an account (rate-limited)" },
      { method: "POST", path: "/api/v1/auth/login", auth: false, description: "Sign in (rate-limited)" },
      { method: "POST", path: "/api/v1/auth/logout", auth: "session", description: "Revoke session (idempotent)" },
      { method: "GET", path: "/api/v1/auth/me", auth: "session", description: "Current user" },
      { method: "GET", path: "/api/v1/auth/activity", auth: "session", description: "Recent audited auth events (redacted)" },
      { method: "POST", path: "/api/v1/identity/sessions", auth: "session", description: "Create NINAuth verification session (PKCE, consent screen contract, optional scopes)" },
      { method: "GET", path: "/api/v1/identity/sessions/:id", auth: "session", description: "Session status + event timeline" },
      { method: "POST", path: "/api/v1/identity/sessions/:id/consent", auth: "session", description: "MOCK NINAuth app consent decision (GRANT/DENY, granular scope subset) — retired in LIVE mode" },
      { method: "POST", path: "/api/v1/identity/sessions/:id/callback", auth: "session", description: "OAuth callback: code exchange (PKCE) + ID token validation → TrustIdentity + evidence + attributes" },
      { method: "GET", path: "/api/v1/identity/me", auth: "session", description: "TrustIdentity + assurance ladder + identifiers + attributes + evidence + consents + timeline + signals (phone/biometric/cross-signal)" },
      { method: "POST", path: "/api/v1/identity/consents/:id/withdraw", auth: "session", description: "NDPA §31 consent withdrawal — revokes sourced attributes + signal identifiers; identity if establishing" },
      { method: "POST", path: "/api/v1/identity/signals/phone/start", auth: "session", description: "Stage 4: start phone OTP verification (NG E.164, consent, hashed OTP, MOCK SMS delivery)" },
      { method: "POST", path: "/api/v1/identity/signals/phone/resend", auth: "session", description: "Stage 4: resend OTP (30s cooldown, max 3, attempts reset)" },
      { method: "POST", path: "/api/v1/identity/signals/phone/confirm", auth: "session", description: "Stage 4: confirm OTP → PHONE identifier (hashed) + evidence → ladder L2" },
      { method: "POST", path: "/api/v1/identity/signals/biometrics/start", auth: "session", description: "Stage 4: create liveness job (MOCK Smile-ID-class contract, consent, 10-min window)" },
      { method: "POST", path: "/api/v1/identity/signals/biometrics/complete", auth: "session", description: "Stage 4: submit capture → verdict (liveness + face-match vs government record) → ladder L3/L4" },
      { method: "GET", path: "/api/v1/passport/me", auth: "session", description: "Stage 5: Trust Passport — score snapshot, credentials, share tokens, receipts, sessions, notifications" },
      { method: "POST", path: "/api/v1/passport/share", auth: "session", description: "Stage 5: create Trust Link (raw token shown ONCE; hashed at rest; view-counted, expiring, revocable)" },
      { method: "GET", path: "/api/v1/passport/share", auth: "session", description: "Stage 5: list share tokens (metadata only)" },
      { method: "DELETE", path: "/api/v1/passport/share/:id", auth: "session", description: "Stage 5: revoke a Trust Link" },
      { method: "GET", path: "/api/v1/passport/public/:token", auth: "public", description: "Stage 5: PUBLIC trust-card view — anti-enumeration, view-counted, receipted (410 when dead, 429 when abused)" },
      { method: "POST", path: "/api/v1/passport/credentials/:id/revoke", auth: "session", description: "Stage 5: manually revoke a passport credential (sticks until re-verification)" },
      { method: "POST", path: "/api/v1/passport/dsr", auth: "session", description: "Stage 5: NDPA §36 DSR — EXPORT (data download, 7-day retention) or DELETE (password-confirmed cascade)" },
      { method: "GET", path: "/api/v1/passport/dsr", auth: "session", description: "Stage 5: list DSR requests" },
      { method: "GET", path: "/api/v1/passport/dsr/:id/export", auth: "session", description: "Stage 5: download a completed data export" },
      { method: "GET", path: "/api/v1/passport/notifications", auth: "session", description: "Stage 5: notification feed (change alerts)" },
      { method: "POST", path: "/api/v1/passport/notifications", auth: "session", description: "Stage 5: mark notifications read ({id} or {all:true})" },
      { method: "GET", path: "/api/v1/passport/score-history", auth: "session", description: "Stage 11: score history — snapshot series, component deltas between consecutive snapshots, audited window events (correlated context, not a verdict)" },
      { method: "GET", path: "/api/v1/passport/score-history/export", auth: "session", description: "Stage 11: self-service series export — ?format=csv|json (audited SCORE_HISTORY_EXPORTED)" },
      { method: "POST", path: "/api/v1/internal/webhook-tick", auth: "internal-token", description: "Stage 12 (internal): timer-driven webhook retry tick — called by the webhook-worker mini-service every 60s; bounded (≤5 due deliveries per call)" },
      { method: "POST", path: "/api/v1/security/sessions/:id/revoke", auth: "session", description: "Stage 5: remote sign-out of another active session" },
      { method: "POST", path: "/api/v1/safety/check", auth: "session", description: "Stage 6: run a Safety Check — exactly one of { handle, phone, link, qr }; anti-enumeration UNAVAILABLE shape; receipted + audited" },
      { method: "GET", path: "/api/v1/safety/checks", auth: "session", description: "Stage 6: verifier's check history + sent trust requests" },
      { method: "GET", path: "/api/v1/safety/me", auth: "session", description: "Stage 6: subject's safety settings, checks received (named), trust requests received" },
      { method: "POST", path: "/api/v1/safety/settings", auth: "session", description: "Stage 6: update standing SAFETY_CHECK consent (enable/disable + scope toggles)" },
      { method: "POST", path: "/api/v1/safety/request", auth: "session", description: "Stage 6: send a trust request to an uncheckable member (7-day expiry, one pending per pair)" },
      { method: "POST", path: "/api/v1/safety/request/:id/respond", auth: "session", description: "Stage 6: subject ACCEPT (mints scoped trust link + runs named assessment) or DECLINE" },
      { method: "POST", path: "/api/v1/reputation/flags", auth: "session", description: "Stage 7: file a flag with evidence (L2 reporter gate, one open per pair, 3/7-day quota, human review)" },
      { method: "GET", path: "/api/v1/reputation/me", auth: "session", description: "Stage 7: flags against me (masked reporters), my filed flags, response/appeal states, anti-gaming eligibility" },
      { method: "POST", path: "/api/v1/reputation/flags/:id/respond", auth: "session", description: "Stage 7: subject's response + evidence → UNDER_REVIEW (human review queue)" },
      { method: "POST", path: "/api/v1/reputation/flags/:id/withdraw", auth: "session", description: "Stage 7: reporter withdraws an OPEN flag (zero score effect)" },
      { method: "POST", path: "/api/v1/reputation/flags/:id/appeal", auth: "session", description: "Stage 7: subject appeals a CONFIRMED flag (once, 14-day window)" },
      { method: "GET", path: "/api/v1/reputation/review", auth: "session+reviewer", description: "Stage 7: HUMAN review queue (REVIEWER role — operational grant)" },
      { method: "POST", path: "/api/v1/reputation/review/:flagId/decision", auth: "session+reviewer", description: "Stage 7: reviewer decides CONFIRMED / UNFOUNDED / DISMISSED with published rationale" },
      { method: "POST", path: "/api/v1/reputation/appeals/:id/decision", auth: "session+reviewer", description: "Stage 7: reviewer decides appeal UPHELD / OVERTURNED (overturn restores the score; decision lifts the fairness freeze)" },
      { method: "GET", path: "/api/v1/engine/public", auth: "public", description: "Stage 8: PUBLIC trust-engine view — active scoring policy (rules, budgets), policy history, DPIA registry status, automated-decision gate" },
      { method: "GET", path: "/api/v1/engine/me", auth: "session", description: "Stage 8: my score's lifecycle state (ACTIVE/STALE/FROZEN), policy provenance, gate state, freeze note" },
      { method: "GET", path: "/api/v1/engine/admin/overview", auth: "session+admin", description: "Stage 8: admin console — snapshot-state distribution, policies, DPIA registry, gate" },
      { method: "POST", path: "/api/v1/engine/admin/policies", auth: "session+admin", description: "Stage 8: create a DRAFT policy version (rules validated + clamped server-side; change summary published)" },
      { method: "POST", path: "/api/v1/engine/admin/policies/:id/activate", auth: "session+admin", description: "Stage 8: activate a draft — REQUIRES a completed DPIA (NDPC gate); retires the previous version; scores recompute" },
      { method: "POST", path: "/api/v1/engine/admin/policies/:id/simulate", auth: "session+admin", description: "Stage 8: read-only impact dry-run — recompute the cohort under draft rules vs active; buckets, transitions, masked movers; nothing is written" },
      { method: "POST", path: "/api/v1/engine/admin/dpia", auth: "session+admin", description: "Stage 8: record a DPIA assessment for a policy (completes only when every checklist item is done)" },
      { method: "POST", path: "/api/v1/engine/admin/gate", auth: "session+admin", description: "Stage 8: toggle automated-significant-decisions (DPIA-gated + typed confirmation; disabling always allowed)" },
      { method: "POST", path: "/api/v1/trust/check", auth: "X-API-Key", description: "Stage 9: Trust Decision API — exactly one of { handle, phone, link, qr }; consent-gated, band-level, receipted to the subject; NOT an automated decision (NDPA §37 note on every response)" },
      { method: "GET", path: "/api/v1/dev/me", auth: "session", description: "Stage 9: developer portal — your API clients, keys (prefixes only), team, quota, 14-day usage, webhook config + deliveries" },
      { method: "POST", path: "/api/v1/dev/clients", auth: "session", description: "Stage 9: register an API client (business app; SANDBOX default; max 3 owned)" },
      { method: "POST", path: "/api/v1/dev/clients/:id/keys", auth: "session+team", description: "Stage 9: mint an API key — raw key returned ONCE, sha256 at rest (OWNER/DEVELOPER)" },
      { method: "POST", path: "/api/v1/dev/keys/:id/revoke", auth: "session+team", description: "Stage 9: revoke an API key — immediate (OWNER/DEVELOPER)" },
      { method: "POST", path: "/api/v1/dev/clients/:id/webhook", auth: "session+team", description: "Stage 9: set/rotate webhook URL + signing secret (secret shown once; LIVE requires https, no localhost)" },
      { method: "POST", path: "/api/v1/dev/clients/:id/webhook/test", auth: "session+team", description: "Stage 9: send a signed WEBHOOK_TEST event and see the delivery result immediately" },
      { method: "GET", path: "/api/v1/dev/clients/:id/decisions", auth: "session+team", description: "Stage 9: the business's decision history (masked inputs, last 50)" },
      { method: "POST", path: "/api/v1/dev/clients/:id/team", auth: "session+owner", description: "Stage 9: add a team member by handle/email with role DEVELOPER or VIEWER" },
      { method: "DELETE", path: "/api/v1/dev/clients/:id/team/:memberId", auth: "session+owner", description: "Stage 9: remove a team member (OWNER row immutable)" },
      { method: "POST", path: "/api/v1/dev/clients/:id/live", auth: "session+owner", description: "Stage 9: switch environment to LIVE (typed confirm; honest MOCK-provider note)" },
      { method: "POST", path: "/api/v1/dev/clients/:id/plan", auth: "session+owner", description: "Stage 9: change plan FREE/STARTER (quotas enforced for real; billing is a mock-up)" },
      { method: "POST", path: "/api/v1/dev/webhook-sink", auth: "public", description: "Stage 9: sandbox self-test webhook sink — echoes headers + body; point your webhook at it to watch deliveries land" },
      { method: "GET", path: "/api/v1/network/me", auth: "session", description: "Stage 10: my Trust Network — membership/consent, graph, pending interactions, standing, own shared signals, k-anonymity rules" },
      { method: "POST", path: "/api/v1/network/membership", auth: "session", description: "Stage 10: join (NETWORK consent minted) or pause (edges stop counting immediately)" },
      { method: "POST", path: "/api/v1/network/interactions", auth: "session", description: "Stage 10: propose a mutual verified interaction by handle (L2+ both sides, 3/7-day quota, 7-day expiry)" },
      { method: "POST", path: "/api/v1/network/interactions/:id/respond", auth: "session", description: "Stage 10: accept or decline a proposal (accept = mutual attestation; both scores recompute)" },
      { method: "POST", path: "/api/v1/network/interactions/:id/revoke", auth: "session", description: "Stage 10: cancel your proposal or revoke an active attestation (immediate, either side)" },
      { method: "GET", path: "/api/v1/network/providers", auth: "public", description: "Stage 10: pan-African country-provider registry (honest MOCK_LIVE / PLANNED depth)" },
    ],
    roadmap: {
      "9": "B2B platform — SHIPPED (developer portal, API keys, webhooks, Trust Decision API)",
      "10": "Trust network — SHIPPED (verified-interaction graph, shared signals, provider registry)",
      "11": "Score insights — SHIPPED (why-did-my-score-change timeline, component deltas, series export)",
    },
  });
}
